### ISSUE TITLE
Current state if the project?

### ISSUE THREAD

**Issue by mxwlf** [tocsoft/Linq2OData#3]
Hi Scott,

I find the problem this project solves very relevant. I see that there are no recent additions. What is the state of this project?

Do you still have time/interest in managing it? respond to push request? I'm currently testing and evaluating if I will use this as part of a project of mine so I don't know how many contributions I will be making. But wanted to check with you first if you are interested in any addition I make. 

The first thing I need to do is take this to .net core. I already made a fork for this.

Thanks!

**Comment by tocsoft** [comment]
The project was largely abandoned but not out of anything other than I am no longer was dependent on it on a daily basis and it was feature complete at the time for what I needed it for, However your interest has inspired me to refresh the library a bit because, update build/ deployment etc move it over the netstandard/netcore. 

I plan to push out a new version to nuget shortly that support netstandard/core. I would be totally happy to receive PRs adding feature/improving the library as it stands.

**Comment by mxwlf** [comment]
Got it, good to hear! I also think this project deserves continuity, specially in the client side. I think asp.net core does a good job supporting servicing. I was about to fire up a PR for the .net core migration but just realized you are ahead of me :) I'll send over your way anything I improve on my side.

**Comment by mxwlf** [comment]
Thanks for releasing to NuGet! 🥇
